### ISSUE TITLE
Надо сортировать ещё и тут

### ISSUE THREAD

**Issue by coursar** [BlackRider116/TOP_posts#1]
https://github.com/BlackRider116/TOP_posts/blob/701f47981f01269f25c7124f0edb436b2fb8f3a7/app.js#L34

Если все существующие посты ушли в минус, а мы добавили новый пост, то он должен быть первым (т.к. у него 0 лайков).

Сейчас же он последний. Поэтому лучше пересортировывать всё при добавлении, а потом делать `rebuildList`.

**Comment by BlackRider116** [comment]
Понятия не имею как это сделать. слишком все сложно сделано из вашего видео примеров, которое применяя в дз, сразу все ломается. и у вас в видео нет подсказки как при добавлении поста отсчитывать положение этого нового поста. только через клик происходит сортировка. видяшки смотрел 3 раза, так ответа и не нашел. как мне кажется, вы усложняете простые вещи, но не учитываете что вам это все понятно, а нам новичкам ни грамма

**Comment by BlackRider116** [comment]
сделано, благодаря подсказке в вк))
